parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $projectDir: '%kernel.project_dir%'

    App\Messenger\MeasureHandler:
        class: App\Messenger\MeasureHandler
        public: true
